def register_reserved(token_list):
    token_list.append(('abs',           'RESERVED_ABS'))
    token_list.append(('access',        'RESERVED_ACCESS'))
    token_list.append(('after',         'RESERVED_AFTER'))
    token_list.append(('alias',         'RESERVED_ALIAS'))
    token_list.append(('all',           'RESERVED_ALL'))
    token_list.append(('and',           'RESERVED_AND'))
    token_list.append(('architecture',  'RESERVED_ARCHITECTURE'))
    token_list.append(('array',         'RESERVED_ARRAY'))
    token_list.append(('assert',        'RESERVED_ASSERT'))
    token_list.append(('assume',        'RESERVED_ASSUME'))
    token_list.append(('attribute',     'RESERVED_ATTRIBUTE'))
    token_list.append(('begin',         'RESERVED_BEGIN'))
    token_list.append(('block',         'RESERVED_BLOCK'))
    token_list.append(('body',          'RESERVED_BODY'))
    token_list.append(('buffer',        'RESERVED_BUFFER'))
    token_list.append(('bus',           'RESERVED_BUS'))
    token_list.append(('case',          'RESERVED_CASE'))
    token_list.append(('component',     'RESERVED_COMPONENT'))
    token_list.append(('configuration', 'RESERVED_CONFIGURATION'))
    token_list.append(('constant',      'RESERVED_CONSTANT'))
    token_list.append(('context',       'RESERVED_CONTEXT'))
    token_list.append(('cover',         'RESERVED_COVER'))
    token_list.append(('default',       'RESERVED_DEFAULT'))
    token_list.append(('disconnect',    'RESERVED_DISCONNECT'))
    token_list.append(('downto',        'RESERVED_DOWNTO'))
    token_list.append(('else',          'RESERVED_ELSE'))
    token_list.append(('elsif',         'RESERVED_ELSIF'))
    token_list.append(('end',           'RESERVED_END'))
    token_list.append(('entity',        'RESERVED_ENTITY'))
    token_list.append(('exit',          'RESERVED_EXIT'))
    token_list.append(('fairness',      'RESERVED_FAIRNESS'))
    token_list.append(('file',          'RESERVED_FILE'))
    token_list.append(('for',           'RESERVED_FOR'))
    token_list.append(('force',         'RESERVED_FORCE'))
    token_list.append(('function',      'RESERVED_FUNCTION'))
    token_list.append(('generate',      'RESERVED_GENERATE'))
    token_list.append(('generic',       'RESERVED_GENERIC'))
    token_list.append(('group',         'RESERVED_GROUP'))
    token_list.append(('guarded',       'RESERVED_GUARDED'))
    token_list.append(('if',            'RESERVED_IF'))
    token_list.append(('impure',        'RESERVED_IMPURE'))
    token_list.append(('in',            'RESERVED_IN'))
    token_list.append(('inertial',      'RESERVED_INERTIAL'))
    token_list.append(('inout',         'RESERVED_INOUT'))
    token_list.append(('is',            'RESERVED_IS'))
    token_list.append(('label',         'RESERVED_LABEL'))
    token_list.append(('library',       'RESERVED_LIBRARY'))
    token_list.append(('linkage',       'RESERVED_LINKAGE'))
    token_list.append(('literal',       'RESERVED_LITERAL'))
    token_list.append(('loop',          'RESERVED_LOOP'))
    token_list.append(('map',           'RESERVED_MAP'))
    token_list.append(('mod',           'RESERVED_MOD'))
    token_list.append(('nand',          'RESERVED_NAND'))
    token_list.append(('new',           'RESERVED_NEW'))
    token_list.append(('next',          'RESERVED_NEXT'))
    token_list.append(('nor',           'RESERVED_NOR'))
    token_list.append(('not',           'RESERVED_NOT'))
    token_list.append(('null',          'RESERVED_NULL'))
    token_list.append(('of',            'RESERVED_OF'))
    token_list.append(('on',            'RESERVED_ON'))
    token_list.append(('open',          'RESERVED_OPEN'))
    token_list.append(('or',            'RESERVED_OR'))
    token_list.append(('others',        'RESERVED_OTHERS'))
    token_list.append(('out',           'RESERVED_OUT'))
    token_list.append(('package',       'RESERVED_PACKAGE'))
    token_list.append(('parameter',     'RESERVED_PARAMETER'))
    token_list.append(('port',          'RESERVED_PORT'))
    token_list.append(('postponed',     'RESERVED_POSTPONED'))
    token_list.append(('procedure',     'RESERVED_PROCEDURE'))
    token_list.append(('process',       'RESERVED_PROCESS'))
    token_list.append(('property',      'RESERVED_PROPERTY'))
    token_list.append(('protected',     'RESERVED_PROTECTED'))
    token_list.append(('private',       'RESERVED_PRIVATE'))
    token_list.append(('pure',          'RESERVED_PURE'))
    token_list.append(('range',         'RESERVED_RANGE'))
    token_list.append(('record',        'RESERVED_RECORD'))
    token_list.append(('register',      'RESERVED_REGISTER'))
    token_list.append(('reject',        'RESERVED_REJECT'))
    token_list.append(('release',       'RESERVED_RELEASE'))
    token_list.append(('rem',           'RESERVED_REM'))
    token_list.append(('report',        'RESERVED_REPORT'))
    token_list.append(('restrict',      'RESERVED_RESTRICT'))
    token_list.append(('return',        'RESERVED_RETURN'))
    token_list.append(('rol',           'RESERVED_ROL'))
    token_list.append(('ror',           'RESERVED_ROR'))
    token_list.append(('select',        'RESERVED_SELECT'))
    token_list.append(('sequence',      'RESERVED_SEQUENCE'))
    token_list.append(('severity',      'RESERVED_SEVERITY'))
    token_list.append(('signal',        'RESERVED_SIGNAL'))
    token_list.append(('shared',        'RESERVED_SHARED'))
    token_list.append(('sla',           'RESERVED_SLA'))
    token_list.append(('sll',           'RESERVED_SLL'))
    token_list.append(('sra',           'RESERVED_SRA'))
    token_list.append(('srl',           'RESERVED_SRL'))
    token_list.append(('strong',        'RESERVED_STRONG'))
    token_list.append(('subtype',       'RESERVED_SUBTYPE'))
    token_list.append(('then',          'RESERVED_THEN'))
    token_list.append(('to',            'RESERVED_TO'))
    token_list.append(('transport',     'RESERVED_TRANSPORT'))
    token_list.append(('type',          'RESERVED_TYPE'))
    token_list.append(('unaffected',    'RESERVED_UNAFFECTED'))
    token_list.append(('units',         'RESERVED_UNITS'))
    token_list.append(('until',         'RESERVED_UNTIL'))
    token_list.append(('use',           'RESERVED_USE'))
    token_list.append(('variable',      'RESERVED_VARIABLE'))
    token_list.append(('view',          'RESERVED_VIEW'))
    token_list.append(('vmode',         'RESERVED_VMODE'))
    token_list.append(('vpkg',          'RESERVED_VPKG'))
    token_list.append(('vprop',         'RESERVED_VPROP'))
    token_list.append(('vunit',         'RESERVED_VUNIT'))
    token_list.append(('wait',          'RESERVED_WAIT'))
    token_list.append(('when',          'RESERVED_WHEN'))
    token_list.append(('while',         'RESERVED_WHILE'))
    token_list.append(('with',          'RESERVED_WITH'))
    token_list.append(('xnor',          'RESERVED_XNOR'))
    token_list.append(('xor',           'RESERVED_XOR'))
#-------------------------------------------------------------------------------

def register_directives(token_list):
    token_list.append(('protect',          'DIRECTIVE_PROTECT'))
    token_list.append(('warning',          'DIRECTIVE_WARNING'))
    token_list.append(('error',            'DIRECTIVE_ERROR'))

    token_list.append(('VHDL_VERSION',     'DIRECTIVE_CONSTANT_BUILTIN'))
    token_list.append(('TOOL_TYPE',        'DIRECTIVE_CONSTANT_BUILTIN'))
    token_list.append(('TOOL_VENDOR',      'DIRECTIVE_CONSTANT_BUILTIN'))
    token_list.append(('TOOL_NAME',        'DIRECTIVE_CONSTANT_BUILTIN'))
    token_list.append(('TOOL_EDITION',     'DIRECTIVE_CONSTANT_BUILTIN'))
    token_list.append(('TOOL_VERSION',     'DIRECTIVE_CONSTANT_BUILTIN'))

    token_list.append(('\r',               'DIRECTIVE_NEWLINE'))
    token_list.append(('\n',               'DIRECTIVE_NEWLINE'))
    token_list.append(('\r\n',             'DIRECTIVE_NEWLINE'))
    token_list.append(('\n\r',             'DIRECTIVE_NEWLINE'))
#-------------------------------------------------------------------------------

def register_delimiters(token_list):
    #- token_list.append(('&',   'DELIMITER_AMPERSAND'))
    #- token_list.append((''',   'DELIMITER_TICK'))
    #- token_list.append(('(',   'DELIMITER_LEFT_PARENTHESIS'))
    #- token_list.append((')',   'DELIMITER_RIGHT_PARENTHESIS'))
    #- token_list.append(('*',   'DELIMITER_MULTIPLY'))
    #- token_list.append(('+',   'DELIMITER_PLUS_SIGN'))
    #- token_list.append((',',   'DELIMITER_COMMA'))
    #- token_list.append(('-',   'DELIMITER_MINUS_SIGN'))
    #- token_list.append(('.',   'DELIMITER_DOT'))
    #- token_list.append(('/',   'DELIMITER_DIVIDE'))
    #- token_list.append((':',   'DELIMITER_COLON'))
    #- token_list.append((';',   'DELIMITER_SEMICOLON'))
    #- token_list.append(('<',   'DELIMITER_LESS_THAN_SIGN'))
    #- token_list.append(('=',   'DELIMITER_EQUALS_SIGN'))
    #- token_list.append(('>',   'DELIMITER_GREATER_THAN_SIGN'))
    token_list.append(('`',   'DELIMITER_GRAVE_ACCENT'))
    #- token_list.append(('|',   'DELIMITER_VERTICAL_BAR'))
    #- token_list.append(('[',   'DELIMITER_LEFT_SQUARE_BRACKET'))
    #- token_list.append((']',   'DELIMITER_RIGHT_SQUARE_BRACKET'))
    #- token_list.append(('?',   'DELIMITER_QUESTION_MARK'))
    #- token_list.append(('@',   'DELIMITER_COMMERCIAL_AT'))
    #- token_list.append(('^',   'DELIMITER_CIRCUMFLEX'))

    #- token_list.append(('=>',  'DELIMITER_ARROW'))
    #- token_list.append(('**',  'DELIMITER_EXPONENTIATE'))
    #- token_list.append((':=',  'DELIMITER_VARIABLE_ASSIGNMENT'))
    #- token_list.append(('/=',  'DELIMITER_INEQUALITY'))
    #- token_list.append(('>=',  'DELIMITER_GREATER_THAN_OR_EQUAL'))
    #- token_list.append(('<=',  'DELIMITER_LESS_THAN_OR_EQUAL'))
    #- token_list.append(('<=',  'DELIMITER_SIGNAL_ASSIGNMENT'))
    token_list.append(('<>',  'DELIMITER_BOX'))
    #- token_list.append(('??',  'DELIMITER_CONDITION_CONVERSION'))
    #- token_list.append(('?=',  'DELIMITER_MATCHING_EQUALITY'))
    #- token_list.append(('?/=', 'DELIMITER_MATCHING_INEQUALITY'))
    #- token_list.append(('?<',  'DELIMITER_MATCHING_LESS_THAN'))
    #- token_list.append(('?<=', 'DELIMITER_MATCHING_LESS_THAN_OR_EQUAL'))
    #- token_list.append(('?>',  'DELIMITER_MATCHING_GREATER_THAN'))
    #- token_list.append(('?>=', 'DELIMITER_MATCHING_GREATER_THAN_OR_EQUAL'))
    #- token_list.append(('<<',  'DELIMITER_DOUBLE_LESS_THAN'))
    #- token_list.append(('>>',  'DELIMITER_DOUBLE_GREATER_THAN'))

    token_list.append(('--',  'LINE_COMMENT_START'))
    token_list.append(('/*',  'BLOCK_COMMENT_START'))
#-------------------------------------------------------------------------------

def register_operator_symbols(token_list):
    token_list.append(('"??"',   'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"and"',  'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"or"',   'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"nand"', 'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"nor"',  'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"xor"',  'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"xnor"', 'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"="',    'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"/="',   'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"<"',    'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"<="',   'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('">"',    'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('">="',   'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"?="',   'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"?/="',  'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"?<"',   'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"?<="',  'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"?>"',   'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"?>="',  'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"sll"',  'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"srl"',  'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"sla"',  'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"sra"',  'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"rol"',  'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"ror"',  'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"+"',    'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"-"',    'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"&"',    'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"*"',    'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"/"',    'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"mod"',  'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"rem"',  'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"**"',   'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"abs"',  'TOKEN_OPERATOR_SYMBOL'))
    token_list.append(('"not"',  'TOKEN_OPERATOR_SYMBOL'))
#-------------------------------------------------------------------------------

def register_attributes(token_list):
    token_list.append(('base',               'ATTRIBUTE_TYPE'))
    token_list.append(('left',               'ATTRIBUTE_VALUE'))
    token_list.append(('right',              'ATTRIBUTE_VALUE'))
    token_list.append(('high',               'ATTRIBUTE_VALUE'))
    token_list.append(('low',                'ATTRIBUTE_VALUE'))
    token_list.append(('ascending',          'ATTRIBUTE_VALUE'))
    token_list.append(('length',             'ATTRIBUTE_PURE_FUNCTION'))
    token_list.append(('range',              'ATTRIBUTE_RANGE'))
    token_list.append(('reverse_range',      'ATTRIBUTE_RANGE'))
    token_list.append(('subtype',            'ATTRIBUTE_SUBTYPE'))
    token_list.append(('image',              'ATTRIBUTE_PURE_FUNCTION'))
    token_list.append(('pos',                'ATTRIBUTE_PURE_FUNCTION'))
    token_list.append(('succ',               'ATTRIBUTE_PURE_FUNCTION'))
    token_list.append(('pred',               'ATTRIBUTE_PURE_FUNCTION'))
    token_list.append(('leftof',             'ATTRIBUTE_PURE_FUNCTION'))
    token_list.append(('rightof',            'ATTRIBUTE_PURE_FUNCTION'))
    token_list.append(('value',              'ATTRIBUTE_PURE_FUNCTION'))
    token_list.append(('val',                'ATTRIBUTE_PURE_FUNCTION'))
    token_list.append(('designated_subtype', 'ATTRIBUTE_SUBTYPE'))
    token_list.append(('reflect',            'ATTRIBUTE_IMPURE_FUNCTION'))
    token_list.append(('left',               'ATTRIBUTE_FUNCTION'))
    token_list.append(('right',              'ATTRIBUTE_FUNCTION'))
    token_list.append(('high',               'ATTRIBUTE_FUNCTION'))
    token_list.append(('low',                'ATTRIBUTE_FUNCTION'))
    token_list.append(('length',             'ATTRIBUTE_FUNCTION'))
    token_list.append(('ascending',          'ATTRIBUTE_FUNCTION'))
    token_list.append(('index',              'ATTRIBUTE_SUBTYPE'))
    token_list.append(('element',            'ATTRIBUTE_SUBTYPE'))
    token_list.append(('delayed',            'ATTRIBUTE_SIGNAL'))
    token_list.append(('stable',             'ATTRIBUTE_SIGNAL'))
    token_list.append(('quiet',              'ATTRIBUTE_SIGNAL'))
    token_list.append(('transaction',        'ATTRIBUTE_SIGNAL'))
    token_list.append(('event',              'ATTRIBUTE_FUNCTION'))
    token_list.append(('active',             'ATTRIBUTE_FUNCTION'))
    token_list.append(('last_event',         'ATTRIBUTE_FUNCTION'))
    token_list.append(('last_active',        'ATTRIBUTE_FUNCTION'))
    token_list.append(('last_value',         'ATTRIBUTE_FUNCTION'))
    token_list.append(('driving',            'ATTRIBUTE_FUNCTION'))
    token_list.append(('driving_value',      'ATTRIBUTE_FUNCTION'))
    token_list.append(('simple_name',        'ATTRIBUTE_VALUE'))
    token_list.append(('instance_name',      'ATTRIBUTE_VALUE'))
    token_list.append(('path_name',          'ATTRIBUTE_VALUE'))
    token_list.append(('record',             'ATTRIBUTE_TYPE'))
    token_list.append(('value',              'ATTRIBUTE_VALUE'))
    token_list.append(('signal',             'ATTRIBUTE_SIGNAL'))
    token_list.append(('converse',           'ATTRIBUTE_MODE_VIEW'))
#-------------------------------------------------------------------------------

def register_base_specifiers(token_list):
    token_list.append(('b',  'BASE_SPECIFIER_BINARY'))
    token_list.append(('o',  'BASE_SPECIFIER_OCTAL'))
    token_list.append(('x',  'BASE_SPECIFIER_HEX'))
    token_list.append(('ub', 'BASE_SPECIFIER_BINARY'))
    token_list.append(('uo', 'BASE_SPECIFIER_OCTAL'))
    token_list.append(('ux', 'BASE_SPECIFIER_HEX'))
    token_list.append(('sb', 'BASE_SPECIFIER_BINARY'))
    token_list.append(('so', 'BASE_SPECIFIER_OCTAL'))
    token_list.append(('sx', 'BASE_SPECIFIER_HEX'))
    token_list.append(('d',  'BASE_SPECIFIER_DECIMAL'))
#-------------------------------------------------------------------------------

def register_core(token_list):
    register_reserved        (token_list)
    register_directives      (token_list)
    register_delimiters      (token_list)
    register_operator_symbols(token_list)
    register_attributes      (token_list)
    register_base_specifiers (token_list)
#-------------------------------------------------------------------------------

