""" These headers contain the "register_*" functions """
from core import *

from libraries.std.env      import *
from libraries.std.standard import *
from libraries.std.textio   import *

from libraries.ieee.std_logic_1164 import *
from libraries.ieee.numeric_std    import *
from libraries.ieee.fixed_pkg      import *
from libraries.ieee.float_pkg      import *
from libraries.ieee.math_real      import *
from libraries.ieee.math_complex   import *
#-------------------------------------------------------------------------------

token_list = []

register_core               (token_list)
register_std_env            (token_list)
register_std_standard       (token_list)
register_std_textio         (token_list)
register_ieee_std_logic_1164(token_list)
register_ieee_numeric_std   (token_list)
register_ieee_fixed_pkg     (token_list)
register_ieee_float_pkg     (token_list)
register_ieee_math_real     (token_list)
register_ieee_math_complex  (token_list)
#-------------------------------------------------------------------------------

class Node:
    def __init__(self):
        self.type = []
        self.next = {}

token_tree = {}

for keyword, type in token_list:
    last = None
    root = token_tree
    for character in keyword.lower():
        if character not in root:
            root[character] = Node()
        if character == '_' and len(root[character].type) == 0:
            root[character].type = [ 'IDENTIFIER_EXPECTING_LETTER' ]
        last = root[character]
        root = last.next
    if last and type not in last.type:
        last.type.insert(0, type)
#-------------------------------------------------------------------------------

def sanitise(character):
    match character:
        case '\n': return '\\n'
        case '\r': return '\\r'
        case _: return character
#-------------------------------------------------------------------------------

def gen_case(file, root, indent = 0):
    if len(root) == 0:
        return

    file.write(indent*' ' + 'switch(lookahead){\n')
    indent += 2;
    for character, node in root.items():
        file.write(indent*' ' + f"case '{sanitise(character)}':\n")

        file.write((indent+2)*' ' + f'lookahead = advance(lexer);\n')
        if len(node.type) > 0:
            file.write((indent+2)*' ' + f'lexer->mark_end(lexer);\n')
            file.write((indent+2)*' ' + '{\n')
            file.write((indent+4)*' ' + 'static const int type_array[] = { ')
            for type in node.type:
                file.write(f'{type}, ')
            file.write('0 };\n')
            file.write((indent+4)*' ' + f'type = type_array;\n')
            file.write((indent+2)*' ' + '}\n')
        else:
            file.write((indent+2)*' ' + f'type = 0;\n')
        gen_case(file, node.next, indent+2)
        file.write((indent+2)*' ' + f'break;\n')

    file.write(indent*' ' + 'default:\n')
    file.write((indent+2)*' ' + 'break;\n')

    indent -= 2
    file.write(indent*' ' + '}\n')
#-------------------------------------------------------------------------------

with open('../src/token_tree_match.inc', 'w', newline='\n', encoding='utf-8') as file:
    file.write('/*------------------------------------------------------------------------------\n')
    file.write('\n')
    file.write('Autogenerated by autogen/gen_token_trie.py\n')
    file.write('------------------------------------------------------------------------------*/\n')
    file.write('\n')
    gen_case(file, token_tree)
    file.write('//------------------------------------------------------------------------------\n')
#-------------------------------------------------------------------------------

