def register_std_env_types(token_list):
    token_list.append(('dayofweek',                       'LIBRARY_TYPE'))
    token_list.append(('time_record',                     'LIBRARY_TYPE'))
    token_list.append(('directory_items',                 'LIBRARY_TYPE'))
    token_list.append(('directory',                       'LIBRARY_TYPE'))
    token_list.append(('dir_open_status',                 'LIBRARY_TYPE'))
    token_list.append(('dir_open_status_range_record',    'LIBRARY_TYPE'))
    token_list.append(('dir_create_status',               'LIBRARY_TYPE'))
    token_list.append(('dir_create_status_range_record',  'LIBRARY_TYPE'))
    token_list.append(('dir_delete_status',               'LIBRARY_TYPE'))
    token_list.append(('dir_delete_status_range_record',  'LIBRARY_TYPE'))
    token_list.append(('file_delete_status',              'LIBRARY_TYPE'))
    token_list.append(('file_delete_status_range_record', 'LIBRARY_TYPE'))
    token_list.append(('call_path_element',               'LIBRARY_TYPE'))
    token_list.append(('call_path_vector',                'LIBRARY_TYPE'))
    token_list.append(('call_path_vector_ptr',            'LIBRARY_TYPE'))
#-------------------------------------------------------------------------------

def register_std_env_constants(token_list):
    token_list.append(('sunday',               'LIBRARY_CONSTANT_ENV'))
    token_list.append(('monday',               'LIBRARY_CONSTANT_ENV'))
    token_list.append(('tuesday',              'LIBRARY_CONSTANT_ENV'))
    token_list.append(('wednesday',            'LIBRARY_CONSTANT_ENV'))
    token_list.append(('thursday',             'LIBRARY_CONSTANT_ENV'))
    token_list.append(('friday',               'LIBRARY_CONSTANT_ENV'))
    token_list.append(('saturday',             'LIBRARY_CONSTANT_ENV'))

    token_list.append(('status_ok',            'LIBRARY_CONSTANT_ENV'))
    token_list.append(('status_not_found',     'LIBRARY_CONSTANT_ENV'))
    token_list.append(('status_no_directory',  'LIBRARY_CONSTANT_ENV'))
    token_list.append(('status_access_denied', 'LIBRARY_CONSTANT_ENV'))
    token_list.append(('status_item_exists',   'LIBRARY_CONSTANT_ENV'))
    token_list.append(('status_not_empty',     'LIBRARY_CONSTANT_ENV'))
    token_list.append(('status_no_file',       'LIBRARY_CONSTANT_ENV'))
    token_list.append(('status_error',         'LIBRARY_CONSTANT_ENV'))

    token_list.append(('dir_separator',        'LIBRARY_CONSTANT_ENV'))
#-------------------------------------------------------------------------------

def register_std_env_functions(token_list):
    token_list.append(('stop',                'LIBRARY_FUNCTION'))
    token_list.append(('finish',              'LIBRARY_FUNCTION'))
    token_list.append(('resolution_limit',    'LIBRARY_FUNCTION'))
    token_list.append(('localtime',           'LIBRARY_FUNCTION'))
    token_list.append(('gmtime',              'LIBRARY_FUNCTION'))
    token_list.append(('epoch',               'LIBRARY_FUNCTION'))
    token_list.append(('time_to_seconds',     'LIBRARY_FUNCTION'))
    token_list.append(('seconds_to_time',     'LIBRARY_FUNCTION'))
    token_list.append(('to_string',           'LIBRARY_FUNCTION'))
    token_list.append(('file_name',           'LIBRARY_FUNCTION'))
    token_list.append(('file_path',           'LIBRARY_FUNCTION'))
    token_list.append(('file_line',           'LIBRARY_FUNCTION'))
    token_list.append(('minimum',             'LIBRARY_FUNCTION'))
    token_list.append(('maximum',             'LIBRARY_FUNCTION'))
    token_list.append(('dir_open',            'LIBRARY_FUNCTION'))
    token_list.append(('dir_close',           'LIBRARY_FUNCTION'))
    token_list.append(('dir_itemexists',      'LIBRARY_FUNCTION'))
    token_list.append(('dir_itemisdir',       'LIBRARY_FUNCTION'))
    token_list.append(('dir_itemisfile',      'LIBRARY_FUNCTION'))
    token_list.append(('dir_workingdir',      'LIBRARY_FUNCTION'))
    token_list.append(('dir_createdir',       'LIBRARY_FUNCTION'))
    token_list.append(('dir_deletedir',       'LIBRARY_FUNCTION'))
    token_list.append(('dir_deletefile',      'LIBRARY_FUNCTION'))
    token_list.append(('getenv',              'LIBRARY_FUNCTION'))
    token_list.append(('vhdl_version',        'LIBRARY_FUNCTION'))
    token_list.append(('tool_type',           'LIBRARY_FUNCTION'))
    token_list.append(('tool_vendor',         'LIBRARY_FUNCTION'))
    token_list.append(('tool_name',           'LIBRARY_FUNCTION'))
    token_list.append(('tool_edition',        'LIBRARY_FUNCTION'))
    token_list.append(('tool_version',        'LIBRARY_FUNCTION'))
    token_list.append(('deallocate',          'LIBRARY_FUNCTION'))
    token_list.append(('get_call_path',       'LIBRARY_FUNCTION'))
    token_list.append(('pslassertfailed',     'LIBRARY_FUNCTION'))
    token_list.append(('psliscovered',        'LIBRARY_FUNCTION'))
    token_list.append(('setpslcoverassert',   'LIBRARY_FUNCTION'))
    token_list.append(('getpslcoverassert',   'LIBRARY_FUNCTION'))
    token_list.append(('pslisassertcovered',  'LIBRARY_FUNCTION'))
    token_list.append(('clearpslstate',       'LIBRARY_FUNCTION'))
    token_list.append(('isvhdlassertfailed',  'LIBRARY_FUNCTION'))
    token_list.append(('getvhdlassertcount',  'LIBRARY_FUNCTION'))
    token_list.append(('clearvhdlassert',     'LIBRARY_FUNCTION'))
    token_list.append(('setvhdlassertenable', 'LIBRARY_FUNCTION'))
    token_list.append(('getvhdlassertenable', 'LIBRARY_FUNCTION'))
    token_list.append(('setvhdlassertformat', 'LIBRARY_FUNCTION'))
    token_list.append(('getvhdlassertformat', 'LIBRARY_FUNCTION'))
    token_list.append(('setvhdlreadseverity', 'LIBRARY_FUNCTION'))
    token_list.append(('getvhdlreadseverity', 'LIBRARY_FUNCTION'))
#-------------------------------------------------------------------------------

def register_std_env_namespaces(token_list):
    token_list.append(('work', 'LIBRARY_NAMESPACE'))
    token_list.append(('std',  'LIBRARY_NAMESPACE'))
    token_list.append(('ieee', 'LIBRARY_NAMESPACE'))
#-------------------------------------------------------------------------------

def register_std_env(token_list):
    register_std_env_types     (token_list)
    register_std_env_constants (token_list)
    register_std_env_functions (token_list)
    register_std_env_namespaces(token_list)
#-------------------------------------------------------------------------------

