def register_std_standard_types(token_list):
    token_list.append(('range_direction',                'LIBRARY_TYPE'))
    token_list.append(('range_direction_range_record',   'LIBRARY_TYPE'))
    token_list.append(('boolean',                        'LIBRARY_TYPE'))
    token_list.append(('boolean_range_record',           'LIBRARY_TYPE'))
    token_list.append(('bit',                            'LIBRARY_TYPE'))
    token_list.append(('bit_range_record',               'LIBRARY_TYPE'))
    token_list.append(('character',                      'LIBRARY_TYPE'))
    token_list.append(('character_range_record',         'LIBRARY_TYPE'))
    token_list.append(('severity_level',                 'LIBRARY_TYPE'))
    token_list.append(('severity_level_range_record',    'LIBRARY_TYPE'))
    token_list.append(('universal_integer_range_record', 'LIBRARY_TYPE'))
    token_list.append(('universal_real',                 'LIBRARY_TYPE'))
    token_list.append(('universal_real_range_record',    'LIBRARY_TYPE'))
    token_list.append(('integer',                        'LIBRARY_TYPE'))
    token_list.append(('integer_range_record',           'LIBRARY_TYPE'))
    token_list.append(('real',                           'LIBRARY_TYPE'))
    token_list.append(('real_range_record',              'LIBRARY_TYPE'))
    token_list.append(('time',                           'LIBRARY_TYPE'))
    token_list.append(('time_range_record',              'LIBRARY_TYPE'))
    token_list.append(('delay_length',                   'LIBRARY_TYPE'))
    token_list.append(('natural',                        'LIBRARY_TYPE'))
    token_list.append(('positive',                       'LIBRARY_TYPE'))
    token_list.append(('string',                         'LIBRARY_TYPE'))
    token_list.append(('boolean_vector',                 'LIBRARY_TYPE'))
    token_list.append(('bit_vector',                     'LIBRARY_TYPE'))
    token_list.append(('integer_vector',                 'LIBRARY_TYPE'))
    token_list.append(('real_vector',                    'LIBRARY_TYPE'))
    token_list.append(('time_vector',                    'LIBRARY_TYPE'))
    token_list.append(('file_open_kind',                 'LIBRARY_TYPE'))
    token_list.append(('file_open_kind_range_record',    'LIBRARY_TYPE'))
    token_list.append(('file_open_status',               'LIBRARY_TYPE'))
    token_list.append(('file_open_status_range_record',  'LIBRARY_TYPE'))
    token_list.append(('file_open_state',                'LIBRARY_TYPE'))
    token_list.append(('file_open_state_range_record',   'LIBRARY_TYPE'))
    token_list.append(('file_origin_kind',               'LIBRARY_TYPE'))
    token_list.append(('file_origin_kind_range_record',  'LIBRARY_TYPE'))
#-------------------------------------------------------------------------------

def register_std_standard_constants(token_list):
    token_list.append(('true',                'LIBRARY_CONSTANT_BOOLEAN'))
    token_list.append(('false',               'LIBRARY_CONSTANT_BOOLEAN'))

    token_list.append(('nul',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('soh',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('stx',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('etx',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('eot',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('enq',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('ack',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('bel',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('bs',                  'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('ht',                  'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('lf',                  'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('vt',                  'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('ff',                  'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('cr',                  'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('so',                  'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('si',                  'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('dle',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('dc1',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('dc2',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('dc3',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('dc4',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('nak',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('syn',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('etb',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('can',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('em',                  'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('sub',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('esc',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('fsp',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('gsp',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('rsp',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('usp',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('del',                 'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c128',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c129',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c130',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c131',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c132',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c133',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c134',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c135',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c136',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c137',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c138',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c139',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c140',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c141',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c142',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c143',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c144',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c145',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c146',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c147',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c148',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c149',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c150',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c151',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c152',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c153',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c154',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c155',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c156',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c157',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c158',                'LIBRARY_CONSTANT_CHARACTER'))
    token_list.append(('c159',                'LIBRARY_CONSTANT_CHARACTER'))

    token_list.append(('note',                'LIBRARY_CONSTANT_DEBUG'))
    token_list.append(('warning',             'LIBRARY_CONSTANT_DEBUG'))
    token_list.append(('error',               'LIBRARY_CONSTANT_DEBUG'))
    token_list.append(('failure',             'LIBRARY_CONSTANT_DEBUG'))

    token_list.append(('ascending',           'LIBRARY_CONSTANT_STANDARD'))
    token_list.append(('descending',          'LIBRARY_CONSTANT_STANDARD'))

    token_list.append(('read_mode',           'LIBRARY_CONSTANT_STANDARD'))
    token_list.append(('write_mode',          'LIBRARY_CONSTANT_STANDARD'))
    token_list.append(('append_mode',         'LIBRARY_CONSTANT_STANDARD'))
    token_list.append(('read_write_mode',     'LIBRARY_CONSTANT_STANDARD'))

    token_list.append(('open_ok',             'LIBRARY_CONSTANT_STANDARD'))
    token_list.append(('name_error',          'LIBRARY_CONSTANT_STANDARD'))
    token_list.append(('mode_error',          'LIBRARY_CONSTANT_STANDARD'))
    #- status_error is defined in standard.h

    token_list.append(('state_open',          'LIBRARY_CONSTANT_STANDARD'))
    token_list.append(('state_closed',        'LIBRARY_CONSTANT_STANDARD'))

    token_list.append(('file_origin_begin',   'LIBRARY_CONSTANT_STANDARD'))
    token_list.append(('file_origin_current', 'LIBRARY_CONSTANT_STANDARD'))
    token_list.append(('file_origin_end',     'LIBRARY_CONSTANT_STANDARD'))

    token_list.append(('fs',                  'LIBRARY_CONSTANT_UNIT'))
    token_list.append(('ps',                  'LIBRARY_CONSTANT_UNIT'))
    token_list.append(('ns',                  'LIBRARY_CONSTANT_UNIT'))
    token_list.append(('us',                  'LIBRARY_CONSTANT_UNIT'))
    token_list.append(('ms',                  'LIBRARY_CONSTANT_UNIT'))
    token_list.append(('sec',                 'LIBRARY_CONSTANT_UNIT'))
    token_list.append(('min',                 'LIBRARY_CONSTANT_UNIT'))
    token_list.append(('hr',                  'LIBRARY_CONSTANT_UNIT'))
#-------------------------------------------------------------------------------

def register_std_standard_functions(token_list):
    token_list.append(('rising_edge',  'LIBRARY_FUNCTION'))
    token_list.append(('falling_edge', 'LIBRARY_FUNCTION'))
    token_list.append(('now',          'LIBRARY_FUNCTION'))
    token_list.append(('to_ostring',   'LIBRARY_FUNCTION'))
    token_list.append(('to_hstring',   'LIBRARY_FUNCTION'))
#-------------------------------------------------------------------------------

def register_std_standard_aliases(token_list):
    token_list.append(('to_bstring',       'LIBRARY_FUNCTION'))
    token_list.append(('to_binary_string', 'LIBRARY_FUNCTION'))
    token_list.append(('to_octal_string',  'LIBRARY_FUNCTION'))
    token_list.append(('to_hex_string',    'LIBRARY_FUNCTION'))
#-------------------------------------------------------------------------------

def register_std_standard_attributes(token_list):
    token_list.append(('foreign', 'LIBRARY_ATTRIBUTE'))
#-------------------------------------------------------------------------------

def register_std_standard(token_list):
    register_std_standard_types     (token_list)
    register_std_standard_constants (token_list)
    register_std_standard_functions (token_list)
    register_std_standard_aliases   (token_list)
    register_std_standard_attributes(token_list)
#-------------------------------------------------------------------------------

