def constants(token_list):
    token_list.append(('math_e',             'LIBRARY_CONSTANT'))
    token_list.append(('math_1_over_e',      'LIBRARY_CONSTANT'))
    token_list.append(('math_pi',            'LIBRARY_CONSTANT'))
    token_list.append(('math_2_pi',          'LIBRARY_CONSTANT'))
    token_list.append(('math_1_over_pi',     'LIBRARY_CONSTANT'))
    token_list.append(('math_pi_over_2',     'LIBRARY_CONSTANT'))
    token_list.append(('math_pi_over_3',     'LIBRARY_CONSTANT'))
    token_list.append(('math_pi_over_4',     'LIBRARY_CONSTANT'))
    token_list.append(('math_3_pi_over_2',   'LIBRARY_CONSTANT'))
    token_list.append(('math_log_of_2',      'LIBRARY_CONSTANT'))
    token_list.append(('math_log_of_10',     'LIBRARY_CONSTANT'))
    token_list.append(('math_log2_of_e',     'LIBRARY_CONSTANT'))
    token_list.append(('math_log10_of_e',    'LIBRARY_CONSTANT'))
    token_list.append(('math_sqrt_2',        'LIBRARY_CONSTANT'))
    token_list.append(('math_1_over_sqrt_2', 'LIBRARY_CONSTANT'))
    token_list.append(('math_sqrt_pi',       'LIBRARY_CONSTANT'))
    token_list.append(('math_deg_to_rad',    'LIBRARY_CONSTANT'))
    token_list.append(('math_rad_to_deg',    'LIBRARY_CONSTANT'))
#-------------------------------------------------------------------------------

def functions(token_list):
    token_list.append(('sign',    'LIBRARY_FUNCTION'))
    token_list.append(('ceil',    'LIBRARY_FUNCTION'))
    token_list.append(('floor',   'LIBRARY_FUNCTION'))
    token_list.append(('round',   'LIBRARY_FUNCTION'))
    token_list.append(('trunc',   'LIBRARY_FUNCTION'))
    token_list.append(('realmax', 'LIBRARY_FUNCTION'))
    token_list.append(('realmin', 'LIBRARY_FUNCTION'))
    token_list.append(('uniform', 'LIBRARY_FUNCTION'))
    token_list.append(('sqrt',    'LIBRARY_FUNCTION'))
    token_list.append(('cbrt',    'LIBRARY_FUNCTION'))
    token_list.append(('exp',     'LIBRARY_FUNCTION'))
    token_list.append(('log',     'LIBRARY_FUNCTION'))
    token_list.append(('log2',    'LIBRARY_FUNCTION'))
    token_list.append(('log10',   'LIBRARY_FUNCTION'))
    token_list.append(('sin',     'LIBRARY_FUNCTION'))
    token_list.append(('cos',     'LIBRARY_FUNCTION'))
    token_list.append(('tan',     'LIBRARY_FUNCTION'))
    token_list.append(('arcsin',  'LIBRARY_FUNCTION'))
    token_list.append(('arccos',  'LIBRARY_FUNCTION'))
    token_list.append(('arctan',  'LIBRARY_FUNCTION'))
    token_list.append(('sinh',    'LIBRARY_FUNCTION'))
    token_list.append(('cosh',    'LIBRARY_FUNCTION'))
    token_list.append(('tanh',    'LIBRARY_FUNCTION'))
    token_list.append(('arcsinh', 'LIBRARY_FUNCTION'))
    token_list.append(('arccosh', 'LIBRARY_FUNCTION'))
    token_list.append(('arctanh', 'LIBRARY_FUNCTION'))
#-------------------------------------------------------------------------------

def register(token_list):
    constants(token_list)
    functions(token_list)
#-------------------------------------------------------------------------------

