name: Publish GitHub release

on:
  push:
    tags: ["v*"]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      attestations: write
    uses: tree-sitter/workflows/.github/workflows/release.yml@main

